class CheckoutPage_locators:
    ADDRESS = "//div[@class='shipping-address-item selected-item']"
    NEW_ADDRESS_BTN = "//span[normalize-space()='Nowy adres']"
    DELVERY_METH_OWN_TR = "//td[@id='label_carrier_flatrate_flatrate']"
    DELVERY_METH_DPD = "//td[@id='label_carrier_Dpdshipping_Dpdshipping']"
    COMMENT_INPUT = "//textarea[@name='customer_notes']"
    NEXT_BTN = "//span[contains(text(),'Następne')]"
    PAYMENT_METH = "//span[@data-bind='text: getTitle()']"
    ORDER_BTN = "//span[contains(text(),'Złóż zamówienie')]"
    STATUS_PAYMENT = "//ul[@class='opc-progress-bar']/li[2]"
    STATUS_DELIVERY = "//ul[@class='opc-progress-bar']/li[1]"
    DISCOUNT_CODE_INPUT = "//input[@id='discount-code']"
    SUBMIT_DISCOUNT = "//span[contains(text(),'Zastosuj zniżkę')]"
    SHOW_DISCOUNT_INPUT = "//span[contains(text(),'Zastosuj kod rabatowy')]"
    # popup with new address
    NA_NAME = "//div[@id='opc-new-shipping-address']/form/div/div/div/input[@name='firstname']"
    NA_SURNAME = "//div[@id='opc-new-shipping-address']/form/div/div/div/input[@name='lastname']"
    NA_COMPANY = "//div[@id='opc-new-shipping-address']/form/div/div/div/input[@name='company']"
    NA_ADDRESS_1 = "//div[@id='opc-new-shipping-address']/form/div/div/div/input[@class='input-text']"
    NA_ADDRESS_2 = ""
    NA_CITY = ""
    NA_REGION = ""
    NA_ZIPCODE = ""
    NA_COUNTRY = ""
    NA_TEL = ""
    SAVE_ADDRESS = "//label[@for='shipping-save-in-address-book']"
